### PR TITLE
Use MPS 2020.3.4

### PR DESCRIPTION
**Pull request by arimer**
Updated locks to MPS 2020.3.4 version.

### CODE REVIEW

**Review by wsafonov — APPROVED** [review]
LGTM. Just need a green build.

**Comment by arimer** [comment]
Yeah, I changed some by accident the version of some other lock files. Just reverted those.

**Comment by arimer** [comment]
Looks like we need an other connection timeout increase for the github actions a well here :/

**Comment by arimer** [comment]
Looks like we have a serious problem when trying to access our nexus repository. I would propose to merge this PR to get the MPS 2020.3.4 artifacts out and afterwards investigate the connection problems to nexus.

**Pull request merged**
