### PR TITLE
Add support for mps backend

### PR DESCRIPTION
**Pull request by giorgosr9**
Refactored the code to add support in order to accept the new feature that we did at mps backend in generate to include and exclude lists of models and solutions.

### CODE REVIEW

**Comment by giorgosr9** [comment]
See also https://github.com/mbeddr/mps-build-backends/pull/5 the feature in the mps backend.

**Comment by HeikoBecker** [comment]
The changes look fine to me.
I have build the project locally and did not run into any error.

As soon as https://github.com/mbeddr/mps-build-backends/pull/5 is ready, this can be merged.

**Comment by sergej-koscejev** [comment]
Please bump the minor version and document the changes in the changelog and readme.

**Comment by sergej-koscejev** [comment]
Also please update the minimum required version of backends here: https://github.com/mbeddr/mps-gradle-plugin/blob/v1.x/src/main/kotlin/de/itemis/mps/gradle/Common.kt#L18

**Comment by sergej-koscejev** [comment]
Thank you @giorgosbekas1995!

**Pull request merged**
